### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by luciusmagn** [stej/rstnpc#1]
https://github.com/stej/rstnpc/blob/b745e4480fac4515342ddb7e9ebfc86ff2841435/01/hello_world/src/csv.rs#L37

You can use `.is_empty()` here.

https://github.com/stej/rstnpc/blob/e5a943c7c12e8d6110a9d0c6a2c7da644bdf0e67/01/hello_world/src/csv.rs#L41-L42

You can use short-hands here and just type `header, rows` :)

Also in most cases, you do not need to take `&Vec<T>` as a parameters, `&[T]` will do and make your code more flexible.

There is also some formatting issues, you can easily fix it by running `cargo fmt` before you commit

**Comment by stej** [comment]
Fixed directly to main.. https://github.com/stej/rstnpc/tree/main/01/hello_world
https://github.com/stej/rstnpc/commit/877b5362f42af71f1f893b7b24006482eb18124e
https://github.com/stej/rstnpc/commit/9189abdc43ad62a292a5f8c92f8a7037f659742b

**Comment by stej** [comment]
Imo it's completed -> closing.
